vim.keymap.set("n", "<S-Up>", "<cmd>resize +1<cr>")
vim.keymap.set("n", "<S-Down>", "<cmd>resize -1<cr>")
vim.keymap.set("n", "<S-Left>", "<cmd>vertical resize -1<cr>")
vim.keymap.set("n", "<S-Right>", "<cmd>vertical resize +1<cr>")
vim.keymap.set("n", "x", '"_x')
vim.keymap.set("n", "dd", '"_dd')
vim.keymap.set("n", "p", '"+p')
vim.keymap.set("n", "P", '"+P')
